backend:
  name: github
  repo: FMatharm/Arche
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: projects
    label: Projects
    folder: src/projects
    create: true
    fields:
      - {label: "Title", name: "project-title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "URL", name: "link", widget: "string"}