backend:
  name: github
  repo: FMatharm/Arche
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: project
    label: Project
    folder: src/projects
    create: true
    slug: "{{project-title}}-{{year}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Project Title"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", default: "../img/placeholder.webp"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "URL", name: "link", widget: "string"}