backend:
  name: github
  repo: FMatharm/Arche
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: project
    label: Project
    folder: src/projects
    create: true
    slug: "{{title}}-{{year}}"
    fields:
      - {label: "Title", name: "title", widget: "string", default: "Project Title", pattern: ['^.{0,29}$', "Must be 29 characters maximum"]}
      - {label: "Featured Image", name: "thumbnail", widget: "image", default: "../img/placeholder.webp"}
      - {label: "Description", name: "description", widget: "text", pattern: ['^.{0,150}$', "Must be 150 characters maximum"]}
      - {label: "URL", name: "link", widget: "string", pattern: ['^https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$', "Must be a valid URL"]}